blank_issues_enabled: false
contact_links:
  - name: âœ‹ Question
    about: You have a question about something you're not sure about
    url: https://github.com/blightio/moar-core-ts/discussions/new
